ARG BASE=ubuntu:24.04@sha256:33ceb71981b602c1a7443a53469e4dba065f7503eab3078a2d7a57a2ab987517

FROM $BASE AS build

ARG BUILD_TYPE="Release"

ARG BUILD_LIBS_TYPE="shared"

ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /rstream/build

WORKDIR /rstream/build

RUN apt-get update && apt-get -y install --no-install-recommends \
    build-essential \
    cmake \
    git \
    gzip \
    jq \
    ninja-build \
    pkg-config \
    python3-dev \
    python3-pip \
    tar

RUN PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install --upgrade conan

RUN --mount=type=cache,target=/root/.conan2 \
    conan profile detect -f

RUN --mount=type=cache,target=/root/.conan2 \
    --mount=type=bind,src=.,target=/rstream/src \
    conan config install /rstream/src/conan/config

ARG CONAN_REMOTE_NAME=rstream

ARG CONAN_REMOTE_URL

ARG CONAN_REMOTE_USERNAME

RUN --mount=type=cache,target=/root/.conan2 \
    if [ -n "${CONAN_REMOTE_URL}" ]; then \
      conan remote list | grep -q "${CONAN_REMOTE_NAME}" || conan remote add "${CONAN_REMOTE_NAME}" "${CONAN_REMOTE_URL}"; \
    fi

RUN --mount=type=cache,target=/root/.conan2 \
    --mount=type=secret,id=password \
    if [ -n "${CONAN_REMOTE_URL}" ] && [ -n "${CONAN_REMOTE_USERNAME}" ]; then \
      conan remote login "${CONAN_REMOTE_NAME}" "${CONAN_REMOTE_USERNAME}" -p "$(cat /run/secrets/password)"; \
    fi

RUN --mount=type=cache,target=/root/.conan2 \
    --mount=type=bind,src=.,target=/rstream/src \
    export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); export TEST_BUILD_FOLDER=/rstream/build/test_package; conan create /rstream/src --build=missing -s:a os.sdk="linux.glibc" -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False")

RUN --mount=type=cache,target=/root/.conan2 \
    --mount=type=bind,src=.,target=/rstream/src \
    export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); export PACKAGE_VERSION=$(conan inspect /rstream/src --format=json | jq -r .version); export PACKAGE_REF=${PACKAGE_NAME}/${PACKAGE_VERSION}@; conan install --requires ${PACKAGE_REF} -s:a os.sdk="linux.glibc" -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") --deployer /rstream/src/deploy.py -of $(pwd)/out

FROM scratch AS final

ARG TARGETPLATFORM

ARG BUILD_LIBS_TYPE="shared"

COPY --from=build /rstream/build/out/ /${TARGETPLATFORM}/glibc/${BUILD_LIBS_TYPE}/
