FROM ubuntu:24.04@sha256:33ceb71981b602c1a7443a53469e4dba065f7503eab3078a2d7a57a2ab987517 AS build

ENV ANDROID_ARCH=armv8

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install --no-install-recommends build-essential git cmake ninja-build tar gzip pkg-config jq

ARG CONAN_VERSION=2.31.2

RUN apt-get update && apt-get -y install --no-install-recommends python3-dev python3-numpy python3-pip && PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install --upgrade "conan==${CONAN_VERSION}"

RUN conan profile detect

ARG CONAN_REMOTE_NAME=rstream

ARG CONAN_REMOTE_URL

ARG CONAN_REMOTE_USERNAME

RUN if [ -n "${CONAN_REMOTE_URL}" ]; then \
      conan remote list | grep -q "${CONAN_REMOTE_NAME}" || conan remote add "${CONAN_REMOTE_NAME}" "${CONAN_REMOTE_URL}"; \
    fi

RUN --mount=type=secret,id=password if [ -n "${CONAN_REMOTE_URL}" ] && [ -n "${CONAN_REMOTE_USERNAME}" ]; then \
      conan remote login "${CONAN_REMOTE_NAME}" "${CONAN_REMOTE_USERNAME}" -p "$(cat /run/secrets/password)"; \
    fi

RUN echo "[settings]\n\
    os=Android\n\
    os.api_level=21\n\
    arch=${ANDROID_ARCH}\n\
    compiler=clang\n\
    compiler.version=14\n\
    build_type=Release\n\
    [options]\n\
    [tool_requires]\n\
    android-ndk/r26b\n\
    [runenv]\n"\
    > /root/.conan2/profiles/android

COPY conanfile.py LICENSE version.txt /rstream/src/

RUN mkdir -p /rstream/build

WORKDIR /rstream/build

ARG BUILD_TYPE="Debug"

ARG BUILD_LIBS_TYPE="static"

RUN export CONAN_SKIP_VERSION_CHECKS=1; export VERSION=tmp; export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); conan install /rstream/src -u -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") --build=missing -pr:b default -pr:h android

COPY . /rstream/src/

RUN export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); conan create /rstream/src -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") -pr:b default -pr:h android

RUN export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); export PACKAGE_VERSION=$(conan inspect /rstream/src --format=json | jq -r .version); export PACKAGE_REF=${PACKAGE_NAME}/${PACKAGE_VERSION}@; conan install --requires ${PACKAGE_REF} -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") -pr:b default -pr:h android --deployer /rstream/src/deploy.py -of $(pwd)/out

FROM scratch AS final

ARG BUILD_LIBS_TYPE="static"

COPY --from=build /rstream/build/out/ /android/${BUILD_LIBS_TYPE}/
