FROM ubuntu:24.04 AS build

ENV ANDROID_ARCH armv8

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y install --no-install-recommends build-essential git cmake ninja-build tar gzip pkg-config jq

RUN apt-get update && apt-get -y install --no-install-recommends python3-dev python3-numpy python3-pip && PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install --upgrade conan

RUN conan profile detect

RUN conan remote add rstream https://nexus.rstream.io/repository/conan

RUN --mount=type=secret,id=password conan remote login rstream admin -p $(cat /run/secrets/password)

RUN echo "[settings]\n\
    os=Android\n\
    os.api_level=21\n\
    arch=${ANDROID_ARCH}\n\
    compiler=clang\n\
    compiler.version=14\n\
    build_type=Release\n\
    [options]\n\
    [tool_requires]\n\
    android-ndk/r26b\n\
    [runenv]\n"\
    > /root/.conan2/profiles/android

COPY conanfile.py COPYING version.txt /rstream/src/

RUN mkdir -p /rstream/build

WORKDIR /rstream/build

ARG BUILD_TYPE="Debug"

ARG BUILD_LIBS_TYPE="static"

RUN export CONAN_SKIP_VERSION_CHECKS=1; export VERSION=tmp; export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); conan install /rstream/src -u -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") --build=missing -pr:b default -pr:h android

COPY . /rstream/src/

RUN export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); conan create /rstream/src -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") -pr:b default -pr:h android

RUN export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); export PACKAGE_VERSION=$(conan inspect /rstream/src --format=json | jq -r .version); export PACKAGE_REF=${PACKAGE_NAME}/${PACKAGE_VERSION}@; conan install --requires ${PACKAGE_REF} -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") -pr:b default -pr:h android --deployer /rstream/src/deploy.py -of $(pwd)/out

FROM scratch AS final

ARG BUILD_LIBS_TYPE="static"

COPY --from=build /rstream/build/out/ /android/${BUILD_LIBS_TYPE}/
