FROM ubuntu:24.04 AS build

ENV MINGW_ARCH x86_64

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y install --no-install-recommends build-essential git cmake ninja-build tar gzip pkg-config jq

RUN apt-get update && apt-get -y install --no-install-recommends python3-dev python3-numpy python3-pip && PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install --upgrade conan

RUN apt-get update && apt-get -y install --no-install-recommends mingw-w64

RUN ln -s /usr/${MINGW_ARCH}-w64-mingw32/include/winioctl.h /usr/${MINGW_ARCH}-w64-mingw32/include/WinIoCtl.h

RUN conan profile detect

RUN conan remote add rstream https://nexus.rstream.io/repository/conan

RUN --mount=type=secret,id=password conan remote login rstream admin -p $(cat /run/secrets/password)

RUN echo "[settings]\n\
    os=Windows\n\
    arch=${MINGW_ARCH}\n\
    compiler=gcc\n\
    compiler.cppstd=20\n\
    compiler.version=13\n\
    compiler.libcxx=libstdc++11\n\
    compiler.threads=win32\n\
    build_type=Release\n\
    [options]\n\
    boost/*:without_stacktrace=True\n\
    [tool_requires]\n\
    [runenv]\n\
    [buildenv]\n\
    CC=${MINGW_ARCH}-w64-mingw32-gcc\n\
    CXX=${MINGW_ARCH}-w64-mingw32-g++\n\
    CPP=${MINGW_ARCH}-w64-mingw32-cpp\n\
    AR=${MINGW_ARCH}-w64-mingw32-ar\n\
    AS=${MINGW_ARCH}-w64-mingw32-as\n\
    GDB=${MINGW_ARCH}-w64-mingw32-gdb\n\
    LD=${MINGW_ARCH}-w64-mingw32-ld\n\
    NM=${MINGW_ARCH}-w64-mingw32-nm\n\
    OBJCOPY=${MINGW_ARCH}-w64-mingw32-objcopy\n\
    OBJDUMP=${MINGW_ARCH}-w64-mingw32-objdump\n\
    RANLIB=${MINGW_ARCH}-w64-mingw32-ranlib\n\
    SIZE=${MINGW_ARCH}-w64-mingw32-size\n\
    STRINGS=${MINGW_ARCH}-w64-mingw32-strings\n\
    STRIP=${MINGW_ARCH}-w64-mingw32-strip\n\
    GCOV=${MINGW_ARCH}-w64-mingw32-gcov\n\
    RC=${MINGW_ARCH}-w64-mingw32-windres\n\
    DLLTOOL=${MINGW_ARCH}-w64-mingw32-dlltool\n"\
    > /root/.conan2/profiles/mingw

COPY conanfile.py COPYING version.txt /rstream/src/

RUN mkdir -p /rstream/build

WORKDIR /rstream/build

ARG BUILD_TYPE="Debug"

ARG BUILD_LIBS_TYPE="static"

RUN export CONAN_SKIP_VERSION_CHECKS=1; export VERSION=tmp; export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); conan install /rstream/src -u -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") --build=missing -pr:b default -pr:h mingw

COPY . /rstream/src/

RUN export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); conan create /rstream/src -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") -pr:b default -pr:h mingw

RUN export PACKAGE_NAME=$(conan inspect /rstream/src --format=json | jq -r .name); export PACKAGE_VERSION=$(conan inspect /rstream/src --format=json | jq -r .version); export PACKAGE_REF=${PACKAGE_NAME}/${PACKAGE_VERSION}@; conan install --requires ${PACKAGE_REF} -s build_type=${BUILD_TYPE} -o ${PACKAGE_NAME}/*:shared=$([ "${BUILD_LIBS_TYPE}" = "shared" ] && echo "True" || echo "False") -pr:b default -pr:h mingw --deployer /rstream/src/deploy.py -of $(pwd)/out

FROM scratch AS final

ARG BUILD_LIBS_TYPE="static"

COPY --from=build /rstream/build/out/ /mingw/${BUILD_LIBS_TYPE}/
