# See LICENSE file in the project root for license information.

add_library(${PROJECT_NAME}-example-python-plugin-interface interface.cpp interface.hpp)
target_compile_definitions(${PROJECT_NAME}-example-python-plugin-interface PRIVATE -DCMAKE_CURRENT_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(${PROJECT_NAME}-example-python-plugin-interface ${PROJECT_NAME}::binding::python Boost::${BOOST_COMPONENT_PYTHON} Python3::Python)
add_library(${PROJECT_NAME}-example-core-plugin-3 ${PLUGIN_LIBRARY_TYPE} plugin_3.cpp)
target_link_libraries(${PROJECT_NAME}-example-core-plugin-3 ${PROJECT_NAME}-example-python-plugin-interface)
add_executable(${PROJECT_NAME}-example-python-plugin main.cpp)
if(ENABLE_STATIC_PLUGINS)
  target_link_libraries(${PROJECT_NAME}-example-python-plugin ${PROJECT_NAME}::plugin::python-wrapper ${PROJECT_NAME}-example-core-plugin-3)
else()
  set_target_properties(${PROJECT_NAME}-example-core-plugin-3 PROPERTIES OUTPUT_NAME ${PROJECT_NAME}-plugin-example-core-plugin-3 PREFIX "")
  add_dependencies(${PROJECT_NAME}-example-python-plugin ${PROJECT_NAME}::plugin::python-wrapper ${PROJECT_NAME}-example-core-plugin-3)
  set(PYTHON_WRAPPER_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/binding/python/plugin/python-wrapper")
  target_compile_definitions(${PROJECT_NAME}-example-python-plugin PRIVATE -DPYTHON_WRAPPER_LIBRARY_OUTPUT_DIRECTORY="${PYTHON_WRAPPER_LIBRARY_OUTPUT_DIRECTORY}")
endif()
target_compile_definitions(${PROJECT_NAME}-example-python-plugin PRIVATE -DCMAKE_CURRENT_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_definitions(${PROJECT_NAME}-example-python-plugin PRIVATE -DCMAKE_CURRENT_BINARY_DIR="${CMAKE_CURRENT_BINARY_DIR}")
target_link_libraries(${PROJECT_NAME}-example-python-plugin Boost::filesystem ${PROJECT_NAME}::core ${PROJECT_NAME}-example-python-plugin-interface)
if(ENABLE_STATIC_PLUGINS)
  target_link_libraries(${PROJECT_NAME}-example-python-plugin ${PROJECT_NAME}::binding::python)
endif()
