# See LICENSE file in the project root for license information.

# LIBSTDCXX

if(STATIC_LIBSTDCXX)
  set(EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX "-static -static-libgcc -static-libstdc++")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX}")
  set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX}")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX}")
endif()

# DEAD_CODE_ELIMINATION

if(DEAD_CODE_ELIMINATION)
  set(EXTRA_CXX_FLAGS_DEAD_CODE_ELIMINATION "-ffunction-sections -fdata-sections")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${EXTRA_CXX_FLAGS_DEAD_CODE_ELIMINATION}")
  set(EXTRA_LINKER_FLAGS_DEAD_CODE_ELIMINATION "-Wl,--gc-sections")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_DEAD_CODE_ELIMINATION}")
  set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_DEAD_CODE_ELIMINATION}")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_DEAD_CODE_ELIMINATION}")
endif()

# OPTIMIZE_FOR_NATIVE

if(OPTIMIZE_FOR_NATIVE)
  include(CheckCXXCompilerFlag)
  check_cxx_compiler_flag("-march=native" COMPILER_SUPPORTS_MARCH_NATIVE)
  if(COMPILER_SUPPORTS_MARCH_NATIVE)
    set(EXTRA_CXX_FLAGS_MARCH_NATIVE "-march=native")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${EXTRA_CXX_FLAGS_MARCH_NATIVE}")
  endif()
  check_cxx_compiler_flag("-mtune=native" COMPILER_SUPPORTS_MTUNE_NATIVE)
  if(COMPILER_SUPPORTS_MTUNE_NATIVE)
    set(EXTRA_CXX_FLAGS_MTUNE_NATIVE "-mtune=native")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${EXTRA_CXX_FLAGS_MTUNE_NATIVE}")
  endif()
endif()

# ENABLE_STATIC_PLUGINS

if(ENABLE_STATIC_PLUGINS)
  add_compile_definitions(RSTREAM_ENABLE_STATIC_PLUGINS)
  set(PLUGIN_LIBRARY_TYPE STATIC)
else()
  set(PLUGIN_LIBRARY_TYPE MODULE)
endif()
