# See LICENSE file in the project root for license information.

set(HOST_SYSTEM_DESCRIPTION "${CMAKE_HOST_SYSTEM}")
if(CMAKE_HOST_SYSTEM_PROCESSOR)
  string(APPEND HOST_SYSTEM_DESCRIPTION " (${CMAKE_HOST_SYSTEM_PROCESSOR})")
endif()
set(TARGET_SYSTEM_DESCRIPTION "${CMAKE_SYSTEM}")
if(CMAKE_SYSTEM_PROCESSOR)
  string(APPEND TARGET_SYSTEM_DESCRIPTION " (${CMAKE_SYSTEM_PROCESSOR})")
endif()

message("")
message("#########################################")
message("\t \t summary")
message("#########################################")
message("build type:                  \t ${CMAKE_BUILD_TYPE}")
message("install prefix:              \t ${CMAKE_INSTALL_PREFIX}")
message("build binaries:              \t ${BUILD_BINS}")
message("build benchmarks:            \t ${BUILD_BENCHMARKS}")
message("build demos:                 \t ${BUILD_DEMOS}")
message("build examples:              \t ${BUILD_EXAMPLES}")
message("testing enabled:             \t ${ENABLE_TESTING}")
message("shared SDK libraries:        \t ${BUILD_SHARED_LIBS}")
message("static plugins:              \t ${ENABLE_STATIC_PLUGINS}")
message("strict warnings:             \t ${ENABLE_STRICT_WARNINGS}")
message("warnings as errors:          \t ${WARNINGS_AS_ERRORS}")
message("clang-tidy:                  \t ${ENABLE_CLANG_TIDY}")
message("include-what-you-use:        \t ${ENABLE_INCLUDE_WHAT_YOU_USE}")
message("cppcheck:                    \t ${ENABLE_CPPCHECK}")
message("host system:                 \t ${HOST_SYSTEM_DESCRIPTION}")
message("target system:               \t ${TARGET_SYSTEM_DESCRIPTION}")
message("C compiler:                  \t ${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION})")
message("C++ compiler:                \t ${CMAKE_CXX_COMPILER} (${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION})")
message("CCache executable:           \t ${CCACHE}")
message("statically link libstdc++:   \t ${STATIC_LIBSTDCXX}")
message("dead code elimination:       \t ${DEAD_CODE_ELIMINATION}")
message("build Java binding:          \t ${BUILD_BINDING_JAVA}")
if(BUILD_BINDING_JAVA)
    message("JNI include directories:     \t ${JNI_INCLUDE_DIRS}")
endif()
message("build Python binding:        \t ${BUILD_BINDING_PYTHON}")
if(BUILD_BINDING_PYTHON)
    message("python3 executable:          \t ${Python3_EXECUTABLE}")
endif()
message("----------------------------------------")
message("version:                     \t ${PROJECT_VERSION}")
message("########################################")
message("")
