# See LICENSE file in the project root for license information.

if(ENABLE_STRICT_WARNINGS AND MSVC)
  string(REGEX REPLACE "[/-]W[0-4]" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
  string(REGEX REPLACE "[/-]W[0-4]" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
endif()

function(rstream_collect_project_targets directory output)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(subdirectory IN LISTS subdirectories)
    rstream_collect_project_targets("${subdirectory}" subdirectory_targets)
    list(APPEND targets ${subdirectory_targets})
  endforeach()
  set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(rstream_enable_project_warnings root_directory)
  if(NOT ENABLE_STRICT_WARNINGS)
    return()
  endif()
  rstream_collect_project_targets("${root_directory}" targets)
  foreach(target IN LISTS targets)
    get_target_property(target_type "${target}" TYPE)
    get_target_property(target_source_dir "${target}" SOURCE_DIR)
    string(FIND "${target_source_dir}/" "${PROJECT_SOURCE_DIR}/external/" external_source_index)
    if(NOT target_type MATCHES "^(EXECUTABLE|MODULE_LIBRARY|OBJECT_LIBRARY|SHARED_LIBRARY|STATIC_LIBRARY)$" OR
       external_source_index EQUAL 0)
      continue()
    endif()
    if(MSVC)
      target_compile_definitions("${target}" PRIVATE BOOST_ASIO_NO_DEPRECATED)
      target_compile_options("${target}" PRIVATE /W4)
      if(WARNINGS_AS_ERRORS)
        target_compile_options("${target}" PRIVATE /WX)
      endif()
    else()
      target_compile_definitions("${target}" PRIVATE BOOST_ASIO_NO_DEPRECATED)
      target_compile_options("${target}" PRIVATE -Wall -Wextra -Wpedantic)
      if(WARNINGS_AS_ERRORS)
        target_compile_options("${target}" PRIVATE -Werror)
      endif()
    endif()
  endforeach()
endfunction()

function(rstream_configure_generated_protobuf_warnings)
  if(NOT ENABLE_STRICT_WARNINGS)
    return()
  endif()
  set(generated_sources ${ARGN})
  list(FILTER generated_sources INCLUDE REGEX "\\.pb\\.cc$")
  if(MSVC)
    set_source_files_properties(
      ${generated_sources}
      PROPERTIES COMPILE_OPTIONS "/wd4100;/wd4251;/wd4267")
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set_source_files_properties(
      ${generated_sources}
      PROPERTIES COMPILE_OPTIONS -Wno-nullability-extension)
  endif()
endfunction()
