# See LICENSE file in the project root for license information.

function(rstream_collect_project_targets directory output)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(subdirectory IN LISTS subdirectories)
    rstream_collect_project_targets("${subdirectory}" subdirectory_targets)
    list(APPEND targets ${subdirectory_targets})
  endforeach()
  set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(rstream_enable_project_warnings root_directory)
  if(NOT ENABLE_STRICT_WARNINGS)
    return()
  endif()
  rstream_collect_project_targets("${root_directory}" targets)
  foreach(target IN LISTS targets)
    get_target_property(target_type "${target}" TYPE)
    get_target_property(target_source_dir "${target}" SOURCE_DIR)
    string(FIND "${target_source_dir}/" "${PROJECT_SOURCE_DIR}/external/" external_source_index)
    if(NOT target_type MATCHES "^(EXECUTABLE|MODULE_LIBRARY|OBJECT_LIBRARY|SHARED_LIBRARY|STATIC_LIBRARY)$" OR
       external_source_index EQUAL 0)
      continue()
    endif()
    if(MSVC)
      target_compile_definitions("${target}" PRIVATE BOOST_ASIO_NO_DEPRECATED)
      target_compile_options("${target}" PRIVATE /W4)
      if(WARNINGS_AS_ERRORS)
        target_compile_options("${target}" PRIVATE /WX)
      endif()
    else()
      target_compile_definitions("${target}" PRIVATE BOOST_ASIO_NO_DEPRECATED)
      target_compile_options("${target}" PRIVATE -Wall -Wextra -Wpedantic)
      if(WARNINGS_AS_ERRORS)
        target_compile_options("${target}" PRIVATE -Werror)
      endif()
    endif()
  endforeach()
endfunction()
