name: Build Stable
on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    if: ${{ github.actor == vars.CI_ALLOWED_ACTOR }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
              conan:
                {
                  channel: "stable",
                  profiles: { build: "default", host: "default" },
                },
            }
    uses: ./.github/workflows/conan.yml
    secrets: inherit
    with:
      build: ${{ toJson(matrix.build) }}
