name: build, package and deploy
on:
  workflow_call:
    inputs:
      build:
        required: true
        type: string
    secrets:
      CONAN_PASSWORD:
        required: false
permissions:
  contents: read
env:
  RSTREAM_URL: "${{ github.ref_type == 'tag' && 'https://rstream.io' || 'https://dev.rstream.io' }}"
  CONAN_REMOTE_NAME: "${{ vars.CONAN_REMOTE_NAME }}"
  CONAN_REMOTE_URL: "${{ vars.CONAN_REMOTE_URL }}"
  CONAN_REMOTE_USERNAME: "${{ vars.CONAN_REMOTE_USERNAME }}"
jobs:
  build:
    if: ${{ github.actor == vars.CI_ALLOWED_ACTOR }}
    strategy:
      fail-fast: true
      matrix:
        build:
          - ${{ fromJSON(inputs.build) }}
    runs-on: ["self-hosted", "Linux"]
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update && sudo apt-get install -y \
            build-essential \
            ccache \
            cmake \
            file \
            git \
            gzip \
            jq \
            ninja-build \
            pipx \
            pkg-config \
            tar \
            xz-utils
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
      - name: install conan
        shell: bash
        run: |
          pipx install conan
          echo "/root/.local/bin/" >> $GITHUB_PATH
      - name: configure conan
        shell: bash
        run: |
          conan profile detect -f
          conan config install conan/config
          if [[ -n "${CONAN_REMOTE_URL}" ]]; then
            remote_name="${CONAN_REMOTE_NAME:-rstream}"
            conan remote list | grep -q "${remote_name}" || conan remote add -f "${remote_name}" "${CONAN_REMOTE_URL}"
            if [[ -n "${CONAN_REMOTE_USERNAME}" ]]; then
              conan remote login "${remote_name}" "${CONAN_REMOTE_USERNAME}" -p "${{ secrets.CONAN_PASSWORD }}"
            fi
          fi
      - name: build
        shell: bash
        run: |
          conan create -u --build=missing --user conan --channel ${{ matrix.build.conan.channel }} -pr:b ${{ matrix.build.conan.profiles.build }} -pr:h ${{ matrix.build.conan.profiles.host }} .
