name: Release-Please
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  release-please:
    if: ${{ github.actor == vars.CI_ALLOWED_ACTOR }}
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@8b8fd2cc23b2e18957157a9d923d75aa0c6f6ad5
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
